### ISSUE TITLE
Reentering a boss room after killing the boss locks you into the room with no way to escape

### ISSUE THREAD

**Issue by Miepee** [randovania/YAMS#214]
:(
![grafik](https://github.com/randovania/YAMS/assets/38186597/6d7bedbf-e99c-4d94-8075-38d59ea80282)

**Comment by DruidVorse** [comment]
lol this also happened with arachnus

**Comment by Miepee** [comment]
yeah am aware. just opted to ignore it back then instead of opening a bug report :see_no_evil:

**Comment by Miepee** [comment]
The fix for arachnus/torizo is relatively simple: just change the `<4` to a `<=4` in oDoor's alarm0
```gml
if (global.event[event] > 0)
{
    if (lock < 4)
        lock = 0
    stayopen = 0
}
```

However, somehow that causes the doors at serris to break. Unsure how to fix that .

**Comment by Miepee** [comment]
The Serris fight calls User0 of oDoor, which is this:
```gml
if (open == 1)
{
    block = instance_create((x - 8), y, oSolid1)
    block.image_yscale = 4
    sfx_play_single(227)
    open = 0
    lockdelay = 2
    showlock = 0
}
```
No idea how the lock influences that lol.
