### ISSUE TITLE
BG3: Gamma South Septogg Helper only spawns AFTER a room reset

### ISSUE THREAD

**Issue by JeffGainsNGames** [randovania/YAMS#215]
this either needs to be:
- changed to have the septogg spawn on gamma death
- removed from logic (bad)

**Comment by Miepee** [comment]
The way that alpha squad works, is that there's an object called `A5_Alpha_Septogg_Checker`
It has only a step event and the following code:

```gml

if ((!instance_exists(oMalpha3TriggerProx)) && (!instance_exists(oMAlpha)))
{
    with (oElderSeptogg)
        ystart = 192
    instance_destroy()
}


```
