### ISSUE TITLE
AM2R: Flashlight not working in Breeding Grounds Fly Stadium Access

### ISSUE THREAD

**Issue by LandofHeros2234** [randovania/YAMS#228]
I went into Breeding Grounds Fly Stadium Access with Flashlight 4 and the room was still dark
In Fly Stadium Access with Flashlight 4
![image](https://github.com/user-attachments/assets/af46b625-7cba-46ff-9cc3-c8039a872ac7)
In Fly Stadium with Flashlight 4
![image](https://github.com/user-attachments/assets/82d706b2-43d1-4f98-ab4b-532b52ffda73)
I am unsure if the bug is for all flashlight levels. The preset I use has one Flashlight item that gives Flashlight 4

**Comment by Miepee** [comment]
I can't reproduce this on 2.8.0-dev5
@LandofHeros2234 what randovania version / yams version were you using? Do you have a yams.json that I can investigate?
