### ISSUE TITLE
add starting items to item history

### ISSUE THREAD

**Issue by JeffGainsNGames** [randovania/YAMS#229]
for completeness starting items *should* probably be shown in this tab.

**Comment by Miepee** [comment]
should they? its more of a log of what you collect, not what you started with

**Comment by JeffGainsNGames** [comment]
I see a world where some may start the game look away then be like "what did I get?" as starting items.

realistically both of these cases (pickups and starting) are also solved with "look at inventory" or tracker but I figured I'd raise the idea.

**Comment by Miepee** [comment]
Eh, fair enough. Shouldnt be too hard:tm:.
